### ISSUE TITLE
peer-to-peer review

### ISSUE THREAD

**Issue by axcell-0** [MozamelJawad/Awesome_Books_ES6#2]
Thanks for sharing your thoughts and comment. If you like what you see please give me a ✴ star

**Comment by axcell-0** [comment]
good job my brother your project is well organised and you have a clean code great job

**Comment by Uzair-Manzoor** [comment]
Great job! Your code is clean and efficient.

**Comment by MozamelJawad** [comment]
Thanks for your nice comments.
